### ISSUE TITLE
"panic: interface conversion: interface {} is nil, not *http.Request" when using auditmgr.MWAudit

### ISSUE THREAD

**Issue by ojalmeida-dc** [digitalcircle-com-br/foundation#2]
### Info

- Branch: v010
- Commit: [0870a0a](https://github.com/digitalcircle-com-br/foundation/commit/0870a0a89cba0cd2fe02293f30873c3e11ae72e1)

### MRE (Minimum Reproducible Example)

```go

func main() {

	db, err := gorm.Open(postgres.New(postgres.Config{
		DSN: "host=localhost port=5432 user=postgres password=postgres dbname=postgres",
	}))

	mustNil(err)

	core.Init("test")
	err = auditmgr.Setup(db)

	mustNil(err)

	router := mux.NewRouter()

	router.PathPrefix("/api").Handler(myHandler{}) // myHandler only
	router.Use(auditmgr.MWAudit)

	http.Handle("/", router)

	err = http.ListenAndServe("localhost:8080", nil)

	mustNil(err)

}

func (myHandler) ServeHTTP(writer http.ResponseWriter, request *http.Request) {

	logrus.Print("reached myHandler")

}

```

### How to reproduce

- start server with `go run main.go`
- make request to 'http://localhost:8080/api'

### Output

```text
2022/08/03 18:09:03 http: panic serving 127.0.0.1:50696: interface conversion: interface {} is nil, not *http.Request
goroutine 40 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1825 +0x148
panic({0xbe15e0, 0xc000286600})
        /usr/local/go/src/runtime/panic.go:844 +0x25a
github.com/digitalcircle-com-br/foundation/lib/ctxmgr.Req({0xd0cb60, 0xc0002865a0})
        /home/otaviano/Documents/Projects/Digital Circle/foundation/lib/ctxmgr/ctx.go:41 +0x88
github.com/digitalcircle-com-br/foundation/lib/ctxmgr.SessionID({0xd0cb60, 0xc0002865a0})
        /home/otaviano/Documents/Projects/Digital Circle/foundation/lib/ctxmgr/ctx.go:50 +0x37
github.com/digitalcircle-com-br/foundation/lib/ctxmgr.Session({0xd0cb60, 0xc0002865a0})
        /home/otaviano/Documents/Projects/Digital Circle/foundation/lib/ctxmgr/ctx.go:99 +0xa5
github.com/digitalcircle-com-br/foundation/lib/auditmgr.Add(0xc000136300)
        /home/otaviano/Documents/Projects/Digital Circle/foundation/lib/auditmgr/auditmgr.go:44 +0xe5
github.com/digitalcircle-com-br/foundation/lib/auditmgr.MWAudit.func1({0xd0c418, 0xc00028a0e0}, 0xc000136300)
        /home/otaviano/Documents/Projects/Digital Circle/foundation/lib/auditmgr/auditmgr.go:70 +0x4f
net/http.HandlerFunc.ServeHTTP(0xc00000e5e8, {0xd0c418, 0xc00028a0e0}, 0xc000136300)
        /usr/local/go/src/net/http/server.go:2084 +0x43
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001700c0, {0xd0c418, 0xc00028a0e0}, 0xc000136300)
        /home/otaviano/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x25d
net/http.(*ServeMux).ServeHTTP(0xfbb1e0, {0xd0c418, 0xc00028a0e0}, 0xc000136100)
        /usr/local/go/src/net/http/server.go:2462 +0x135
net/http.serverHandler.ServeHTTP({0xc00028a000}, {0xd0c418, 0xc00028a0e0}, 0xc000136100)
        /usr/local/go/src/net/http/server.go:2916 +0x474
net/http.(*conn).serve(0xc0002841e0, {0xd0cab8, 0xc0001403c0})
        /usr/local/go/src/net/http/server.go:1966 +0x193c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x9cf

```

**Comment by ojalmeida-dc** [comment]
Seems that it is missing a context value insertion on auditmgr.MWAudit, but even with it inserted (see code below), the error persists

### Before
```go

func MWAudit(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		nr := Add(r)
		if nr == nil {
			http.Error(w, "Error processing audit entry", http.StatusInternalServerError)
			return
		}
		//Since we are leaving session and other stuff here, this is required. d
		nr = nr.WithContext(r.Context())
		h.ServeHTTP(w, nr)
	})
}

```

### After

```go

func MWAudit(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		nr := Add(r)
		if nr == nil {
			http.Error(w, "Error processing audit entry", http.StatusInternalServerError)
			return
		}
		//Since we are leaving session and other stuff here, this is required. d
		newCtx := context.WithValue(r.Context(), model.CTX_REQ, r)
		nr = nr.WithContext(newCtx)
		h.ServeHTTP(w, nr)
	})
}

```
